name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the Repository
      - name: Checkout code
        uses: actions/checkout@v4
      
      # 2. Download and Extract the Docker Images
      - name: Download and extract the Docker images
        run: |
          git clone https://github.com/lanmower/container2wasm-coder
      
      # 3. Build the Docker Images
      - name: Build the Docker image
        run: |
          cd container2wasm-coder
          chmod +x create-images.sh
          ./create-images.sh
      
      # 5. Upload the Pages Artifact
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./container2wasm-coder/out/
      
      # 6. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
