name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the Repository
      - name: Checkout code
        uses: actions/checkout@v4
      
      # 2. Build the Docker Image and Generate Outputs
      - name: Build the Docker image
        run: |
          git clone https://github.com/lanmower/container2wasm-coder
          cd container2wasm-coder
          chmod +x create-images.sh
          ./create-images.sh
      
      # 3. Debugging Step: List All Files
      - name: List files for debugging
        run: |
          echo "Listing all files and directories:"
          ls -R
      
      # 4. Upload the `./out` Directory as an Artifact
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./out/
      
      # 5. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
