name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build the Docker image
        run: |
          wget https://github.com/lanmower/container2wasm-coder/archive/refs/tags/main.tar.gz
          tar -xf main.tar.gz
          ./create-images.sh
      
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          path: ./out/
          token: ${{ secrets.GITHUB_TOKEN }} # This is automatically provided by GitHub Actions
