name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: |
        export PATH=$PATH:$(pwd)
        wget https://github.com/lanmower/container2wasm-coder/archive/refs/tags/main.tar.gz
        tar -xf main.tar.gz
        ./create-images.sh
        
    # Ensure the 'out' directory exists after the build
    - name: Verify out directory exists
      run: |
        if [ -d "./out" ]; then
          echo "The out directory exists."
        else
          echo "The out directory does not exist." && exit 1
        fi

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
      with:
        path: ./out/  # Path to the folder with your output files

    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: ./out/  # Path to the folder with your output files
