name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write
  pages: write
  id-token: write
  actions: write # Give permission to delete artifacts

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Clean up old artifacts
        run: |
          echo "Cleaning up old artifacts..."
          DAYS_TO_KEEP=7
          DATE=$(date --date="$DAYS_TO_KEEP days ago" +%Y-%m-%d)
          for artifact in $(gh api repos/:owner/:repo/actions/artifacts --jq '.artifacts[] | select(.created_at < "'$DATE'T00:00:00Z") | .id'); do
            echo "Deleting artifact $artifact"
            gh api repos/:owner/:repo/actions/artifacts/$artifact -X DELETE
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the Repository
      - name: Checkout code
        uses: actions/checkout@v4
      
      # 2. Download and Extract the Docker Images
      - name: Download and extract the Docker images
        run: |
          git clone https://github.com/lanmower/container2wasm-coder
      
      # 3. Build the Docker Images
      - name: Build the Docker image
        run: |
          cd container2wasm-coder
          chmod +x create-images.sh
          ./create-images.sh
      
      # 5. Upload the Pages Artifact
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./container2wasm-coder/out/
      
      # 6. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

