name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: |
        wget https://github.com/lanmower/container2wasm-coder/archive/refs/tags/main.tar.gz
        tar -xf main.tar.gz
        ./create-images.sh
        
    # Ensure the 'out' directory exists after the build
    - name: Verify out directory exists
      run: |
        if [ -d "./out" ]; then
          echo "The out directory exists."
        else
          echo "The out directory does not exist." && exit 1
        fi
      
    - name: Upload output artifacts
      uses: actions/upload-artifact@v3
      with:
        name: out-artifact
        path: ./out/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download output artifacts
      uses: actions/download-artifact@v3
      with:
        name: out-artifact
    
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # This will be automatically provided by GitHub Actions
