name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/docker
            /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ hashFiles('**/requirements.txt') }} # Use specific files to create a stable key
          restore-keys: |
            ${{ runner.os }}-docker-
        
      - name: Build the Docker image
        run: |
          wget https://github.com/lanmower/container2wasm-coder/archive/refs/tags/main.tar.gz
          tar -xf main.tar.gz
          ./create-images.sh
      
      # Ensure the 'out' directory exists after the build
      - name: Verify out directory exists
        id: verify_out
        run: |
          if [ -d "./out" ]; then
            echo "The out directory exists."
          else
            echo "The out directory does not exist." && exit 1
          fi

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          path: ./out/  # Directly specify the path to your `out` directory
          token: ${{ secrets.GITHUB_TOKEN }}  # This is automatically provided by GitHub Actions
